"""Experiment configuration - Spectral Lie Transport (SLT).

SLT reframes fusion as transport on the unit sphere of normalised spectra (the
manifold on which SAM *is* the geodesic distance).  The base point is the
LR-derived direction; a learned tangent vector is transported through the
spherical exponential map, and intensity is carried by the observation, so the
network's only degrees of freedom are geodesic displacements.

The data, degradation and metric modules are imported from proposal1.daetf, so
every number this package produces is generated by the same protocol the rest
of the repository audits against.
"""

from __future__ import annotations

import math
from dataclasses import asdict, dataclass
from typing import Optional, Sequence, Tuple

from proposal1.daetf.io_utils import discover_dataset, infer_channels


@dataclass
class Config:
    # --- data (None => auto-discover) --------------------------------------
    source_root: Optional[str] = None
    target_root: Optional[str] = None
    bands: Optional[int] = None
    msi_bands: Optional[int] = None
    scale: int = 4
    patch: int = 96

    # --- model --------------------------------------------------------------
    width: int = 48                      # encoder feature width
    depth: int = 3                       # encoder blocks
    blur_ksize: int = 9

    # --- manifold parameterisation (the contribution) -----------------------
    manifold: bool = True                # False => Euclidean residual (stage 1)
    geodesic: bool = True                # exp-map transport; False => add+renorm
    use_msi_guide: bool = False          # tangent conditioned on the HR-MSI guide
    fix_intensity: bool = True           # intensity := ||Y_0||, never learned
    max_angle_rad: float = 1.4           # clamp the tangent magnitude (stable)

    # --- degradation simulation (protocol parity with P1) -------------------
    sigma_range: Tuple[float, float] = (0.6, 2.4)
    aniso: float = 0.5
    noise_range: Tuple[float, float] = (0.0, 0.03)
    srf_jitter: float = 0.35
    eval_sigma: float = 1.2

    # --- optimisation --------------------------------------------------------
    iters: int = 2000                    # ~1.2h on P100; scale up for full convergence
    batch: int = 12
    lr: float = 2e-4
    min_lr: float = 1e-6
    warmup: int = 200
    grad_clip: float = 1.0
    amp: bool = True
    grad_accum: int = 2
    ema_decay: float = 0.999
    n_restarts: int = 1
    workers: int = 2
    seed: int = 42
    cache_limit: int = 12

    # --- loss weights --------------------------------------------------------
    w_geo: float = 1.0                   # squared tangent transport residual
    w_sam: float = 1.0                   # SAM (radians) directly
    w_recon: float = 1.0                 # L1 on the absolute output
    w_grad: float = 0.3                  # spatial gradient (Euclidean stage only)

    # --- bookkeeping ---------------------------------------------------------
    out_dir: str = "./slt_out"
    val_every: int = 500
    log_every: int = 200
    val_scenes: int = 8
    name: str = "slt"

    def __post_init__(self) -> None:
        assert self.patch % self.scale == 0, "patch must be divisible by scale"
        assert 0.0 < self.max_angle_rad <= math.pi

    def resolve(self, source_hints: Sequence[str] = ("cave",),
                target_hints: Sequence[str] = ("harvard",),
                verbose: bool = True) -> "Config":
        """Fill in any field still set to None. Idempotent."""
        if self.source_root is None:
            self.source_root = discover_dataset(source_hints, verbose=verbose)
        if self.target_root is None:
            self.target_root = discover_dataset(target_hints, required=False,
                                                verbose=verbose)
        if self.bands is None or self.msi_bands is None:
            b, m = infer_channels(self.source_root)
            self.bands = self.bands or b
            self.msi_bands = self.msi_bands or m
            if verbose:
                print(f"[config] inferred bands={self.bands} "
                      f"msi_bands={self.msi_bands}")
        return self

    def to_dict(self) -> dict:
        return asdict(self)